// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahgrycidxhfysguwgpjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZ3J5Y2lkeGhmeXNndXdncGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjkwOTQsImV4cCI6MjA3MTEwNTA5NH0.xtTzHML6uqznxtd6H6bxf7ZzwkD0-MlHocQxy72-GF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});